package com.model;
// Generated 2016-5-26 21:17:33 by Hibernate Tools 5.1.0.Alpha1

/**
 * Doctor generated by hbm2java
 */
public class Doctor implements java.io.Serializable {

	private int id;
	private String name;
	private String describe;
	private Integer telephone;
	private int depId;
	private int hid;
	private String level;
	private int fee;
	private String scheduling;

	public Doctor() {
	}

	public Doctor(int id, String name, int depId, int hid, String level, int fee, String scheduling) {
		this.id = id;
		this.name = name;
		this.depId = depId;
		this.hid = hid;
		this.level = level;
		this.fee = fee;
		this.scheduling = scheduling;
	}

	public Doctor(int id, String name, String describe, Integer telephone, int depId, int hid, String level, int fee,
			String scheduling) {
		this.id = id;
		this.name = name;
		this.describe = describe;
		this.telephone = telephone;
		this.depId = depId;
		this.hid = hid;
		this.level = level;
		this.fee = fee;
		this.scheduling = scheduling;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescribe() {
		return this.describe;
	}

	public void setDescribe(String describe) {
		this.describe = describe;
	}

	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	public int getDepId() {
		return this.depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}

	public int getHid() {
		return this.hid;
	}

	public void setHid(int hid) {
		this.hid = hid;
	}

	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	public int getFee() {
		return this.fee;
	}

	public void setFee(int fee) {
		this.fee = fee;
	}

	public String getScheduling() {
		return this.scheduling;
	}

	public void setScheduling(String scheduling) {
		this.scheduling = scheduling;
	}

}
