package com.model;
// Generated 2016-5-28 20:34:30 by Hibernate Tools 5.1.0.Alpha1

/**
 * HospitalDepartment generated by hbm2java
 */
public class HospitalDepartment implements java.io.Serializable {

	private HospitalDepartmentId id;

	public HospitalDepartment() {
	}

	public HospitalDepartment(HospitalDepartmentId id) {
		this.id = id;
	}

	public HospitalDepartmentId getId() {
		return this.id;
	}

	public void setId(HospitalDepartmentId id) {
		this.id = id;
	}

}
