package com.model;
// Generated 2016-5-28 20:34:30 by Hibernate Tools 5.1.0.Alpha1

/**
 * HospitalDepartmentId generated by hbm2java
 */
public class HospitalDepartmentId implements java.io.Serializable {

	private int id;
	private int hid;
	private int depId;

	public HospitalDepartmentId() {
	}

	public HospitalDepartmentId(int id, int hid, int depId) {
		this.id = id;
		this.hid = hid;
		this.depId = depId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getHid() {
		return this.hid;
	}

	public void setHid(int hid) {
		this.hid = hid;
	}

	public int getDepId() {
		return this.depId;
	}

	public void setDepId(int depId) {
		this.depId = depId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospitalDepartmentId))
			return false;
		HospitalDepartmentId castOther = (HospitalDepartmentId) other;

		return (this.getId() == castOther.getId()) && (this.getHid() == castOther.getHid())
				&& (this.getDepId() == castOther.getDepId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getHid();
		result = 37 * result + this.getDepId();
		return result;
	}

}
